import { PlanDay } from "./types";

export const INITIAL_PLAN: PlanDay[] = [
  {
    id: "day_1",
    dayNumber: 1,
    block1_DSA_Concept: "Arrays basics & Prefix Sum algorithms",
    block1_completed: false,
    block2_DSA_Problems: "Solve 8 Easy + 2 Medium problems (e.g., Running Sum, Subarray Sum Equals K)",
    block2_completed: false,
    block3_CF_Upsolve: "Solve 3 Codeforces problems in 800–1000 rating band",
    block3_completed: false,
    block4_ML_Theory: "Linear Regression mathematics, cost functions, gradient descent derivation",
    block4_completed: false,
    block5_ML_Project: "Implement simple & multiple Linear Regression from scratch using NumPy",
    block5_completed: false,
    notes: "Day 1 baseline focus. Ensure learning how prefix sum turns O(N^2) query ranges into O(1).",
    resources: "Prefix sum tutorial, Ordinary Least Squares gradient derivation.",
    problemsList: "LeetCode 303. Range Sum Query - Immutable\nLeetCode 560. Subarray Sum Equals K\nCodeforces 1800A, 1800B, 1800C",
    projectsList: "Linear Regression from Scratch with adaptive learning rate",
    isBacklog: false,
    completed: false
  },
  {
    id: "day_2",
    dayNumber: 2,
    block1_DSA_Concept: "Two-Pointer techniques (Opposite direction, same direction)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 Two-Pointer problems (e.g., Two Sum II, Container With Most Water)",
    block2_completed: false,
    block3_CF_Upsolve: "Simulate virtual participation in Codeforces Div3 contest",
    block3_completed: false,
    block4_ML_Theory: "Logistic Regression model, sigmoid function, cross-entropy loss function derivation",
    block4_completed: false,
    block5_ML_Project: "Implement binary Logistic Regression from scratch with gradient descent",
    block5_completed: false,
    notes: "Two-pointer helps optimize space. Sigmoid scales prediction output to interval (0, 1).",
    resources: "Stanford CS229 Logistic Regression notes, Two pointer visual guide.",
    problemsList: "LeetCode 167. Two Sum II\nLeetCode 11. Container With Most Water\nLeetCode 15. 3Sum",
    projectsList: "Logistic Regression Classifier from Scratch applied to Iris dataset",
    isBacklog: false,
    completed: false
  },
  {
    id: "day_3",
    dayNumber: 3,
    block1_DSA_Concept: "Binary Search (Standard array bounds, search space reduction)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 Binary Search problems (e.g., Search in Rotated Sorted Array, Koko Eating Bananas)",
    block2_completed: false,
    block3_CF_Upsolve: "Upsolve 2-3 complex problems from yesterday's simulated Div3 contest",
    block3_completed: false,
    block4_ML_Theory: "Support Vector Machines (SVM) intuition, margins, support vectors, hypeplane optimization",
    block4_completed: false,
    block5_ML_Project: "Implement SVM classifier with Scikit-Learn, experiment with different margins & kernels (RBF, linear)",
    block5_completed: false,
    notes: "Binary search on answers is an extremely common competitive programming trick.",
    resources: "Mit 6.046J Lecture 4: Binary Search Trees. SVM Margin Optimization notes.",
    problemsList: "LeetCode 33. Search in Rotated Sorted Array\nLeetCode 875. Koko Eating Bananas\nCodeforces 1613C",
    projectsList: "SVM Kernels & C-parameter margin performance visual comparison notebook",
    isBacklog: false,
    completed: false
  },
  {
    id: "day_4",
    dayNumber: 4,
    block1_DSA_Concept: "Sorting Algorithms (Merge Sort, Quick Sort) & C++ STL / Python built-ins",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 Sorting & custom comparator problems (e.g., Merge Intervals)",
    block2_completed: false,
    block3_CF_Upsolve: "Solve 3-4 problems (900-1100 rating)",
    block3_completed: false,
    block4_ML_Theory: "Decision Trees, Information Gain, Shannon Entropy, Gini Impurity, tree splitting math",
    block4_completed: false,
    block5_ML_Project: "Implement a basic Decision Tree node splitter from scratch in Python",
    block5_completed: false,
    notes: "Comparators are critical when sorting structures on custom dimensions.",
    resources: "CLRS Chapter 2 & 7: Sorting. ID3 / C4.5 tree splitting theory.",
    problemsList: "LeetCode 56. Merge Intervals\nLeetCode 179. Largest Number",
    projectsList: "Recursive Entropy Splitter from Scratch on weather data",
    isBacklog: false,
    completed: false
  },
  {
    id: "day_5",
    dayNumber: 5,
    block1_DSA_Concept: "Strings & Character indexing arrays",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 String manipulation problems (e.g., Valid Palindrome II, Longest Palindromic Substring)",
    block2_completed: false,
    block3_CF_Upsolve: "Simulate or run yesterday's active CF Div3 Contest",
    block3_completed: false,
    block4_ML_Theory: "Ensemble learning: Bagging vs Boosting, Random Forests, AdaBoost concept",
    block4_completed: false,
    block5_ML_Project: "Compare Random Forest model against a single Decision Tree on complex datasets",
    block5_completed: false,
    notes: "String matching can often be optimized using sliding window patterns.",
    resources: "Ensemble Learning tutorials, Random Forests mathematical averaging.",
    problemsList: "LeetCode 680. Valid Palindrome II\nLeetCode 5. Longest Palindromic Substring",
    projectsList: "Bagging vs. Boosting Accuracy benchmark with hyperparameter grids",
    isBacklog: false,
    completed: false
  },
  {
    id: "day_6",
    dayNumber: 6,
    block1_DSA_Concept: "Sliding Window algorithms (Fixed sized windows, global max finders)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 Sliding Window problems (e.g., Longest Substring Without Repeating Characters)",
    block2_completed: false,
    block3_CF_Upsolve: "Upsolve yesterday's Div3 problems.",
    block3_completed: false,
    block4_ML_Theory: "Bias-Variance Tradeoff, L1 (Lasso) vs L2 (Ridge) Regularization math formulas",
    block4_completed: false,
    block5_ML_Project: "Implement L1/L2 ridge-lasso effects onto regression models, plot shrinkage rates",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_7",
    dayNumber: 7,
    block1_DSA_Concept: "Revision: Week 1 Foundations (Arrays, Binary Search, Pointers, Windows)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 15 mixed-topic revision problems under strict timers",
    block2_completed: false,
    block3_CF_Upsolve: "Rest day for contests, focus on upsolving pending logs.",
    block3_completed: false,
    block4_ML_Theory: "Comprehensive Revision: Classical ML Algorithms, regularizations, cost functions",
    block4_completed: false,
    block5_ML_Project: "Build a single Mini ML summary notebook gathering all your scratch estimators",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_8",
    dayNumber: 8,
    block1_DSA_Concept: "Recursion fundamentals (Call stack, base cases, structural induction)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 8 Recursion problems (e.g., Subsets, Permutations)",
    block2_completed: false,
    block3_CF_Upsolve: "Solve 2 medium problems (1100–1200 rating band)",
    block3_completed: false,
    block4_ML_Theory: "Reinforcement Learning: Markov Decision Processes (MDP), state transitions, Bellman Optimality Equations",
    block4_completed: false,
    block5_ML_Project: "Create a simple symbolic Markov core grid representing state values",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_9",
    dayNumber: 9,
    block1_DSA_Concept: "Backtracking (Decision state resets, pruning search spaces)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 8–10 Backtracking problems (e.g., N-Queens, Sudoku Solver)",
    block2_completed: false,
    block3_CF_Upsolve: "Simulate virtual participation in Codeforces Div3 contest",
    block3_completed: false,
    block4_ML_Theory: "RL Value Iteration: Dynamic programming state evaluation",
    block4_completed: false,
    block5_ML_Project: "Implement Value Iteration solver on a 5x5 Gridworld matrix",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_10",
    dayNumber: 10,
    block1_DSA_Concept: "Linked List (Node references, reverse, cycle detection)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 Linked List problems (e.g., Reverse Linked List, Linked List Cycle)",
    block2_completed: false,
    block3_CF_Upsolve: "Upsolve yesterday's simulated contest",
    block3_completed: false,
    block4_ML_Theory: "RL Policy Iteration: Alternating Policy Evaluation & Policy Improvement phases",
    block4_completed: false,
    block5_ML_Project: "Implement & optimize Policy Iteration in Gridworld, compare speed against Value Iteration",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_11",
    dayNumber: 11,
    block1_DSA_Concept: "Stack Data Structure (LIFO, monotonic stack, parentheses matching)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 Stack problems (e.g., Min Stack, Daily Temperatures)",
    block2_completed: false,
    block3_CF_Upsolve: "Practice 3 problems (1100-1300 rating)",
    block3_completed: false,
    block4_ML_Theory: "Model-Free RL: Temporal Difference learning, Tabular Q-Learning math",
    block4_completed: false,
    block5_ML_Project: "Implement Tabular Q-Learning from scratch on OpenAI Gym Taxi-v3 / custom loop",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_12",
    dayNumber: 12,
    block1_DSA_Concept: "Queue / Deque & Sliding Window Maximum using Deque",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 Queue/Deque problems (e.g., Implement Stack using Queues, Sliding Window Maximum)",
    block2_completed: false,
    block3_CF_Upsolve: "Active CF Virtual Contest (Div3 or Div2)",
    block3_completed: false,
    block4_ML_Theory: "On-Policy RL: SARSA (State-Action-Reward-State-Action) update formulas",
    block4_completed: false,
    block5_ML_Project: "Implement SARSA agent and compare exploratory trajectories with off-policy Q-Learning",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_13",
    dayNumber: 13,
    block1_DSA_Concept: "Recursion & Backtracking Mixed Practice",
    block1_completed: false,
    block2_DSA_Problems: "Solve 15 mixed-topic recursion-backtracking intermediate puzzles",
    block2_completed: false,
    block3_CF_Upsolve: "Upsolve yesterday's contest gaps.",
    block3_completed: false,
    block4_ML_Theory: "Deep Reinforcement Learning (Deep RL): Deep Q-Networks (DQN) mechanics, experience replay, target networks",
    block4_completed: false,
    block5_ML_Project: "Design core architecture layers of a DQN training loop (ReplayBuffer + Q-Network target updater)",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_14",
    dayNumber: 14,
    block1_DSA_Concept: "Comprehensive Revision: Week 2 recursion, linked lists, stacks, and queues",
    block1_completed: false,
    block2_DSA_Problems: "Solve 20 assorted structural problems under time constraints",
    block2_completed: false,
    block3_CF_Upsolve: "Contest reset day: clean your CF task lists",
    block3_completed: false,
    block4_ML_Theory: "RL Full Revision: MDPs, Bellman, Dynamic Programming, and Model-Free updates",
    block4_completed: false,
    block5_ML_Project: "Refactor gridworld and tabular reinforcement agents into a singular, clean package",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_15",
    dayNumber: 15,
    block1_DSA_Concept: "Trees Basics & Traversal paradigms (Inorder, Preorder, Postorder)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 8 Tree structure problems (e.g., Maximum Depth of Binary Tree, Same Tree)",
    block2_completed: false,
    block3_CF_Upsolve: "CF Practice (1200-1400 rating)",
    block3_completed: false,
    block4_ML_Theory: "Policy-Based RL: Policy Gradient Theorem, REINFORCE algorithm log-likelihood updates",
    block4_completed: false,
    block5_ML_Project: "Implement a basic REINFORCE policy network training loop in PyTorch / Keras / NumPy",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_16",
    dayNumber: 16,
    block1_DSA_Concept: "Binary Trees & Breadth-First-Search (BFS Level Order)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 Binary tree pathing problems (e.g., Binary Tree Level Order Traversal, Path Sum III)",
    block2_completed: false,
    block3_CF_Upsolve: "Codeforces Div2 virtual contest participation",
    block3_completed: false,
    block4_ML_Theory: "Actor-Critic methods (A2C): combining actor policies with baseline value estimation functions",
    block4_completed: false,
    block5_ML_Project: "Draft actor and critic modules with shared features, evaluate benefit on cartpole scenarios",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_17",
    dayNumber: 17,
    block1_DSA_Concept: "Binary Search Trees (BST invariants, insertions, deletions)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 BST problems (e.g., Validate Binary Search Tree, Insert into a Binary Search Tree)",
    block2_completed: false,
    block3_CF_Upsolve: "Upsolve yesterday's Div2 contest",
    block3_completed: false,
    block4_ML_Theory: "Proximal Policy Optimization (PPO): Clipped surrogates, trust regions, variance reduction",
    block4_completed: false,
    block5_ML_Project: "Set up a clean paper review markdown documenting PPO mathematical stability proofs",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_18",
    dayNumber: 18,
    block1_DSA_Concept: "Heaps / Priority Queues (Binary Heaps array layout, sift-up, sift-down)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 Heap problems (e.g., Kth Largest Element, Top K Frequent Elements)",
    block2_completed: false,
    block3_CF_Upsolve: "Practice 3-4 problems focusing on greediness / sorting (1300–1400 band)",
    block3_completed: false,
    block4_ML_Theory: "Natural Language Processing (NLP) Basics: Tokenization methods, Word2Vec, GloVe embeddings, Skip-Gram architecture",
    block4_completed: false,
    block5_ML_Project: "Train a Word2Vec model on a dummy text document chunk from scratch using Python",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_19",
    dayNumber: 19,
    block1_DSA_Concept: "Graphs representation (Adjacency Matrix, Adjacency List) & DFS/BFS sweeps",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 Graph traversal problems (e.g., Number of Islands, Clone Graph)",
    block2_completed: false,
    block3_CF_Upsolve: "Simulate virtual participation in Codeforces Div2 / Div3 contest",
    block3_completed: false,
    block4_ML_Theory: "Sequential NLP models: Recurrent Neural Networks (RNN) backprop through time, LSTM gated states",
    block4_completed: false,
    block5_ML_Project: "Construct a manual LSTM cell block in numpy, detailing input, forget, and output gate computations",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_20",
    dayNumber: 20,
    block1_DSA_Concept: "Graphs (Topological Sort, Cycle Detection in Directed/Undirected graphs)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 12 topological sorting and connected components tasks (e.g., Course Schedule)",
    block2_completed: false,
    block3_CF_Upsolve: "Upsolve yesterday's contest",
    block3_completed: false,
    block4_ML_Theory: "Transformers Deep Revision: self-attention equations, query-key-value scaling, positional encoding, multi-head layouts",
    block4_completed: false,
    block5_ML_Project: "Code Multi-Head Self-Attention matrix math from scratch using PyTorch / NumPy",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_21",
    dayNumber: 21,
    block1_DSA_Concept: "Revision: Week 3 structures (Trees, BSTs, Heaps, and Graph navigations)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 20 intermediate-hard challenges",
    block2_completed: false,
    block3_CF_Upsolve: "Check active CP standings and revision errors",
    block3_completed: false,
    block4_ML_Theory: "RL + NLP Fusion Revision: Actor-Critic mechanics, sequence tokenizers, and attention patterns",
    block4_completed: false,
    block5_ML_Project: "Build an unified summary demonstrating Word2Vec skip-grams alongside policy graphs",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_22",
    dayNumber: 22,
    block1_DSA_Concept: "Shortest Paths (Dijkstra's Algorithm on weighted positive charts)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 8 Shortest Path problems (e.g., Network Delay Time, Path with Maximum Probability)",
    block2_completed: false,
    block3_CF_Upsolve: "CF Problem-solving practice (1300-1500 rating)",
    block3_completed: false,
    block4_ML_Theory: "NLP Translation models, Encoder-Decoder architectures",
    block4_completed: false,
    block5_ML_Project: "Start an NLP text translation / seq2seq summarization model project with pre-trained weights",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_23",
    dayNumber: 23,
    block1_DSA_Concept: "Disjoint Set Union (Union-Find) with path compression and rank optimization",
    block1_completed: false,
    block2_DSA_Problems: "Solve 8 DSU problems (e.g., Number of Provinces, Redundant Connection)",
    block2_completed: false,
    block3_CF_Upsolve: "Virtual participate in a live / archived contest",
    block3_completed: false,
    block4_ML_Theory: "HuggingFace Transformers pipelines & Fine-tuning parameters",
    block4_completed: false,
    block5_ML_Project: "Fine-tune Bert on double datasets for custom sentiment evaluation (Project Continuation)",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_24",
    dayNumber: 24,
    block1_DSA_Concept: "Dynamic Programming (DP fundamentals, memorization vs tabulation, Fibonacci and Knapsack grid)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 DP state identification tasks (e.g., Climb Stairs, Coin Change, House Robber)",
    block2_completed: false,
    block3_CF_Upsolve: "Upsolve yesterday's contest",
    block3_completed: false,
    block4_ML_Theory: "Deep RL Projects: Gym Environment setups and parameters",
    block4_completed: false,
    block5_ML_Project: "Start a custom deep reinforcement learning Gym training run (e.g., PPO or DQN on LunarLander)",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_25",
    dayNumber: 25,
    block1_DSA_Concept: "DP patterns (Two-dimensional DP, grid paths, Coin Change II)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 Patterned DP challenges (e.g., Unique Paths, Longest Common Subsequence)",
    block2_completed: false,
    block3_CF_Upsolve: "CF practice in 1400-1500 rating limit",
    block3_completed: false,
    block4_ML_Theory: "Deep RL reward-shaping mechanisms & penalty models",
    block4_completed: false,
    block5_ML_Project: "Train, modify, and optimize DQN / PPO agent policies (Policy Gym Project Continuation)",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_26",
    dayNumber: 26,
    block1_DSA_Concept: "Advanced DP (Interval DP, Bitmask DP intuition)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 advanced state-space DP formulations",
    block2_completed: false,
    block3_CF_Upsolve: "CF Div2 virtual participation",
    block3_completed: false,
    block4_ML_Theory: "Hyperparameter tuning techniques for large seq2seq networks",
    block4_completed: false,
    block5_ML_Project: "Complete and polish your fine-tuned BERT Transformer / Seq2Seq Translator model",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_27",
    dayNumber: 27,
    block1_DSA_Concept: "Mixed DP & Graph optimization challenges",
    block1_completed: false,
    block2_DSA_Problems: "Solve 12 Hard mixed challenges under 4h restriction",
    block2_completed: false,
    block3_CF_Upsolve: "Upsolve yesterday's Div2 contest",
    block3_completed: false,
    block4_ML_Theory: "Reinforcement models deployment to runtime configurations",
    block4_completed: false,
    block5_ML_Project: "Bundle up and polish your Deep RL LunarLander agent model, save video evaluations",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_28",
    dayNumber: 28,
    block1_DSA_Concept: "Weak Areas Revision (DSU, Dijkstra or Monotonic trees)",
    block1_completed: false,
    block2_DSA_Problems: "Solve 15 target problems picked from personal failures logs",
    block2_completed: false,
    block3_CF_Upsolve: "Upsolve custom CF rating items",
    block3_completed: false,
    block4_ML_Theory: "Computer Vision (CV) basics: Convolution operations, pooling, kernels, classic CNN architectures",
    block4_completed: false,
    block5_ML_Project: "Implement a Conv2D forwarding loop from scratch in raw numpy",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_29",
    dayNumber: 29,
    block1_DSA_Concept: "Full Simulation Contest Day (Mock assessment)",
    block1_completed: false,
    block2_DSA_Problems: "Perform a full 5-problem 3-hour competitive programming mock contest",
    block2_completed: false,
    block3_CF_Upsolve: "Upsolve all failures of the mock exam immediately",
    block3_completed: false,
    block4_ML_Theory: "Final comprehensive theoretical recap: ML, RL, and Deep NLP",
    block4_completed: false,
    block5_ML_Project: "Prepare an unified slide deck reporting ML modeling architectures and scratch results",
    block5_completed: false,
    isBacklog: false,
    completed: false
  },
  {
    id: "day_30",
    dayNumber: 30,
    block1_DSA_Concept: "Ultimate Final Review: Mixed hard problems",
    block1_completed: false,
    block2_DSA_Problems: "Solve 10 mixed advanced structures",
    block2_completed: false,
    block3_CF_Upsolve: "Live Codeforces contest participation (Div2 / Div3 / Global)",
    block3_completed: false,
    block4_ML_Theory: "Mentorship review, mapping forward learning pathways",
    block4_completed: false,
    block5_ML_Project: "Publish, document, and package your 30-day coding repository on GitHub",
    block5_completed: false,
    isBacklog: false,
    completed: false
  }
];
